### ISSUE TITLE
When will the pre-trained weights uploaded

### ISSUE THREAD

**Issue by FeiBryantkit** [qhfan/RMT#26]

**Comment by Snowwwwwwwwwww** [comment]
You may address the author's other projects, but none of these projects have provided complete details, such as pre-trained weights. Despite numerous GitHub issues, the authors have chosen to disregard them😅. This raises doubts about whether the authors actually conducted any experiments for their published works🤨.

Authors should prioritize taking responsibility for their open-source projects, particularly in the context of papers published in prestigious conferences. @qhfan

**Comment by qhfan** [comment]
Thanks your attention to our work, we have updated the weights and the code.

**Comment by qhfan** [comment]
Thank you for your attention to our work. Since the code and weights were organized by someone else, there might inevitably be some discrepancies. I have updated the repository with the original code and weights. Furthermore, I do not believe that it is very polite to casually question someone else's work, especially when we have already made the training logs publicly available. @Snowwwwwwwwwww
